### ISSUE TITLE
پروژه

### ISSUE THREAD

**Issue by S-Ali-S** [Jooyeshgar/web-developer-roadmap#1]
سلام
آیا برای نوشتن پروژه ها میتوانیم از فریم ورک ها استفاده کنیم؟
آیا نوشتن پروژه ذکر شده در اخر لیست کفایت میکنه؟

**Comment by hadi60** [comment]
سلام
به صورت خلاصه خیر
قرار که کار آموزی داشته باشیم شما اگر که قبلا کار کردید نباید برای کاراموزی درخواست می دادید باید به عنوان برنامه نویس درخواست بدید و رزومه به شکل دیگه ای بررسی می شه
ما مطالبی که باید بلد باشید رو اونجا گذاشتیم و انتظار داریم که همه رو بلد باشید مثلا اگر هیچ دانشی در مورد لینوکس یا ورژن کنترل نداشته باشید می تونید پروژه نهایی رو انجام بدید ولی برای ما کفایت نمی کنه
بلد بودن تک تک اون موارد برای ما مهمه و پروژه بهانه است
قبل از یاد گرفتم پی اچ پی خام استفاده از فریم ورک ها اشتباه
