### ISSUE TITLE
خطای 403 هنگام push کردن 

### ISSUE THREAD

**Issue by shimasaberi123** [Jooyeshgar/web-developer-roadmap#3]
سلام خسته نباشید ببخشید 
من یه پروژه کلون کردم یه تغییراتی دادم و میخوام push  کنم 
خطای 403 میده 
برای تمرین میخواستم اینکارو کنم 
نام کاربری و رمز عبورم درسته 
ممنون میشم اگه کسی میدونست راهنمایی کنه

**Comment by hadi60** [comment]
شما باید از پروژه فورک بگیری روی دکمه فورک بالا کلیک کن یه کپی برای خودت ایجاد می شه بعد به اون پروزه می تونی پوش کنی
